[versions]
kotlin = "1.6.10"
coroutines = "1.6.0"
androidxlifecycle = "2.4.1"
okhttp = "4.9.3"
apollo = "3.2.1"
coil = "1.4.0"
ktlint = "0.45.1"

[libraries]
android-pluginGradle = "com.android.tools.build:gradle:7.2.0"

androidx-core = "androidx.core:core-ktx:1.7.0"
androidx-activity = "androidx.activity:activity-ktx:1.4.0"
androidx-lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidxlifecycle" }
androidx-lifecycle-viewmodel-savedstate = { module = "androidx.lifecycle:lifecycle-viewmodel-savedstate", version.ref = "androidxlifecycle" }
androidx-material = "com.google.android.material:material:1.5.0"
androidx-constraintlayout = "androidx.constraintlayout:constraintlayout:2.1.3"
androidx-security-crypto = "androidx.security:security-crypto:1.0.0"
androidx-startup = "androidx.startup:startup-runtime:1.1.1"
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version = "1.7.0" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version = "1.4.1" }
androidx-fragment-ktx = { group = "androidx.fragment", name = "fragment-ktx", version = "1.4.0" }
recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version = "1.2.1" }

mimeTypeDetector = { group = "org.overviewproject", name = "mime-types", version = "1.0.2" }
touchImageView = { group = "com.github.MikeOrtiz", name = "TouchImageView", version = "3.1.1" }

google-material = { group = "com.google.android.material", name = "material", version = "1.5.0" }

kotlin-pluginGradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin" }
kotlin-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }
kotlin-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "coroutines" }
kotlin-serialization-json = "org.jetbrains.kotlinx:kotlinx-serialization-json:1.3.2"
kotlin-serialization-pluginGradle = { module = "org.jetbrains.kotlin:kotlin-serialization", version.ref = "kotlin" }
kotlin-datetime = "org.jetbrains.kotlinx:kotlinx-datetime:0.3.2"

ktlint-pluginGradle = "org.jlleitschuh.gradle:ktlint-gradle:10.2.1"

okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
okhttp-logging = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp" }
retrofit = "com.squareup.retrofit2:retrofit:2.9.0"
retrofit-kotlin-serialization = "com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter:0.8.0"
jwtdecode = "com.auth0.android:jwtdecode:2.0.1"
apollo-pluginGradle = { group = "com.apollographql.apollo3", name = "apollo-gradle-plugin", version.ref = "apollo" }
apollo-runtime = { group = "com.apollographql.apollo3", name = "apollo-runtime", version.ref = "apollo" }
apollo-cache = { group = "com.apollographql.apollo3", name = "apollo-normalized-cache", version.ref = "apollo" }
apollo-cache-sqlite = { group = "com.apollographql.apollo3", name = "apollo-normalized-cache-sqlite", version.ref = "apollo" }
apollo-adapters = { group = "com.apollographql.apollo3", name = "apollo-adapters", version.ref = "apollo" }

coilCore = { group = "io.coil-kt", name = "coil", version.ref = "coil" }

uuid = "com.benasher44:uuid:0.4.0"

junit = "junit:junit:4.13.2"
turbine = "app.cash.turbine:turbine:0.7.0"
mockk = "io.mockk:mockk:1.12.3"